branches:
  - main
plugins:
  - ["@semantic-release/commit-analyzer@10", {"preset": "conventionalcommits"}]
  - ["@semantic-release/release-notes-generator", {"preset": "conventionalcommits"}]
  - "@semantic-release/github"
