name: Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Conventional Commits Standard
        run: npm install -g conventional-changelog-conventionalcommits
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
