name: Release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          git-push: false

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
